export const categories = [
  {
    tag: "bags",
    name: "Bags",
    image: "/categories/bag.png",
    subCategories: [
      { searchTag: "purse", name: "Purse" },
      { searchTag: "bags", name: "Bags" },
      { searchTag: "briefcase", name: "Briefcase" },
      { searchTag: "money-clip", name: "Money Clip" },
      { searchTag: "wallet", name: "Wallet" },
      { searchTag: "backpack", name: "Backpack" },
      { searchTag: "travel-bag", name: "Travel Bag" },
      { searchTag: "card-holder", name: "Card Holder" },
      { searchTag: "laptop-bag", name: "Laptop Bag" },
      { searchTag: "suitcase", name: "Suitcase" },
      { searchTag: "waist-bag", name: "Waist Bag" },
      { searchTag: "hand-bag", name: "Hand Bag" },
      { searchTag: "gift-box", name: "Gift Box" },
    ],
  },
  {
    tag: "shoes",
    name: "Shoes",
    image: "/categories/shoes.png",
    subCategories: [
      { searchTag: "men-shoes", name: "Men Shoes" },
      { searchTag: "men-boots", name: "Men Boots" },
      { searchTag: "ladies-shoes", name: "Ladies Shoes" },
      { searchTag: "ladies-boot", name: "Ladies Boot" },
      { searchTag: "high-heels", name: "High Heels" },
      { searchTag: "formal-shoes", name: "Formal Shoes" },
      { searchTag: "sandals", name: "Sandals" },
      { searchTag: "running-shoes", name: "Running Shoes" },
      { searchTag: "casual-shoes", name: "Casual Shoes" },
      { searchTag: "loafers", name: "Loafers" },
      { searchTag: "sports-shoes", name: "Sports Shoes" },
      { searchTag: "baby-shoes", name: "Baby Shoes" },
      { searchTag: "low-top-shoes", name: "Low Top Shoes" },
      { searchTag: "rain-boots", name: "Rain Boots" },
      { searchTag: "football-shoes", name: "Football Shoes" },
      { searchTag: "slippers", name: "Slippers" },
    ],
  },
  {
    tag: "jewelry",
    name: "Jewelry",
    image: "/categories/jewelry.png",
    subCategories: [
      { searchTag: "men-bracelets", name: "Men Bracelets" },
      { searchTag: "women-bracelets", name: "Women Bracelets" },
      { searchTag: "earrings", name: "Earrings" },
      { searchTag: "jewelry-cases", name: "Jewelry Cases" },
      { searchTag: "necklace", name: "Necklace" },
      { searchTag: "bridal-jewelry", name: "Bridal Jewelry" },
      { searchTag: "crown", name: "Crown" },
      { searchTag: "pendant", name: "Pendant" },
      { searchTag: "bangle", name: "Bangle" },
      { searchTag: "ring", name: "Ring" },
      { searchTag: "anklet", name: "Anklet" },
      { searchTag: "tiara", name: "Tiara" },
      { searchTag: "belly-chain", name: "Belly Chain" },
      { searchTag: "jewelry-box", name: "Jewelry Box" },
      { searchTag: "pin-brooch", name: "Pin Brooch" },
      { searchTag: "fashion-jewelry", name: "Fashion Jewelry" },
    ],
  },
  {
    tag: "beauty-products",
    name: "Beauty Products",
    image: "/categories/beauty.png",
    subCategories: [
      { searchTag: "eyeshadow", name: "Eyeshadow" },
      { searchTag: "eyeliner", name: "Eyeliner" },
      { searchTag: "earrings", name: "Earrings" },
      { searchTag: "face-cream", name: "Face Powder" },
      { searchTag: "makeup-remover", name: "Makeup Remover" },
      { searchTag: "eye-brushes", name: "Eye Brushes" },
      { searchTag: "hair-removal", name: "Hair Removal" },
      { searchTag: "mirror", name: "Mirror" },
      { searchTag: "teeth-whitening", name: "Teeth Whitening" },
      { searchTag: "nail-polish", name: "Nail Polish" },
      { searchTag: "lip-gloss", name: "Lip Gloss" },
      { searchTag: "lip-liner", name: "Lip Liner" },
      { searchTag: "lipstick", name: "Lipstick" },
      { searchTag: "anti-hair-loss", name: "Anti Hair Loss" },
      { searchTag: "hairspray", name: "Hairspray" },
      { searchTag: "hair-dryers", name: "Hair Dryers" },
      { searchTag: "hair-dye", name: "Hair Dye" },
      { searchTag: "hair-oil", name: "Hair Oil" },
      { searchTag: "shower-gel", name: "Shower Gel" },
      { searchTag: "candles", name: "Candles" },
      { searchTag: "lotion", name: "Lotion" },
      { searchTag: "perfume", name: "Perfume" },
      { searchTag: "perfume-set", name: "Perfume Set" },
      { searchTag: "deodorant", name: "Deodorant" },
      { searchTag: "soap", name: "Soap" },
      { searchTag: "body-wash", name: "Body Wash" },
      { searchTag: "hair-conditioner", name: "Hair Conditioner" },
      { searchTag: "toner", name: "Toner" },
      { searchTag: "facial-mask", name: "Facial Mask" },
      { searchTag: "face-moisturizer", name: "Face Moisturizer" },
      { searchTag: "face-serum", name: "Face Serum" },
      { searchTag: "sunscreen", name: "Sunscreen" },
    ],
  },
  {
    tag: "mens-clothing",
    name: "Mens Clothing",
    image: "/categories/mens-clothing.png",
    subCategories: [
      { searchTag: "casual-pants-men", name: "Casual Pants For Men" },
      { searchTag: "jeans-men", name: "Mens Jeans Pant" },
      { searchTag: "suit-men", name: "Men Suit" },
      { searchTag: "leather-jackets-men", name: "Leather Jackets For Men" },
      { searchTag: "trousers-men", name: "Trouser" },
      { searchTag: "shirt-men", name: "Shirts" },
      { searchTag: "shorts-men", name: "Shorts" },
      { searchTag: "tie-clips", name: "Tie Clips" },
      { searchTag: "mens-sweater", name: "Mens Sweater" },
      { searchTag: "underwear-boxer", name: "Boxers" },
      { searchTag: "mens-hat", name: "Mens Hat" },
      { searchTag: "leather-gloves", name: "Leather Gloves" },
      { searchTag: "sweatpants-men", name: "Men Sweatpants" },
      { searchTag: "socks-men", name: "Socks" },
      { searchTag: "tie-men", name: "Tie" },
      { searchTag: "bow-ties", name: "Bow Ties" },
      { searchTag: "gloves", name: "Gloves" },
    ],
  },
  {
    tag: "womens-clothing",
    name: "Womens Clothing",
    image: "/categories/womens-clothing.png",
    subCategories: [
      { searchTag: "hoodies-women", name: "Hoodies & Sweatshirts" },
      { searchTag: "suits-women", name: "Womens Suits Blazers" },
      { searchTag: "bodysuits-women", name: "Bodysuits" },
      { searchTag: "jacket-women", name: "Coats Jackets" },
      { searchTag: "swimwear-women", name: "Swimwear" },
      { searchTag: "bikini-set", name: "Bikini Set" },
      { searchTag: "skirt", name: "Skirt" },
      { searchTag: "womens-jeans", name: "Womens Jeans" },
      { searchTag: "wedding-dresses", name: "Wedding Dresses" },
      { searchTag: "prom-dresses", name: "Prom Dresses" },
      { searchTag: "evening-dresses", name: "Evening Dresses" },
      { searchTag: "cosplay-costumes", name: "Cosplay Costumes" },
      { searchTag: "bra", name: "Bra" },
      { searchTag: "panties", name: "Panties" },
      { searchTag: "women-socks", name: "Women Socks" },
      { searchTag: "bucket-hats", name: "Bucket Hats" },
      { searchTag: "belt-women", name: "Belts" },
    ],
  },
  {
    tag: "baby-items",
    name: "Baby Items",
    image: "/categories/baby-items.png",
    subCategories: [
      { searchTag: "baby-bottle", name: "Baby Bottle" },
      { searchTag: "diapers", name: "Diapers" },
      { searchTag: "potty-&-washing", name: "Potty & Washing" },
      { searchTag: "water-toys", name: "Water Toys" },
      { searchTag: "remote-control-toys", name: "Remote Control Toys" },
      { searchTag: "baby-gift-set", name: "Baby Gift Set" },
      { searchTag: "baby-dress", name: "Baby Dress" },
      { searchTag: "baby-socks", name: "Baby Socks" },
      { searchTag: "baby-swimsuit", name: "Baby Swimsuit" },
      { searchTag: "baby-jacket", name: "Baby Jacket" },
      { searchTag: "baby-skirt", name: "Baby Skirt" },
      { searchTag: "baby-sweater", name: "Baby Sweater" },
      { searchTag: "baby-shoes", name: "Baby Shoes" },
      { searchTag: "baby-sports-shoes", name: "Baby Sports Shoes" },
    ],
  },
  {
    tag: "sunglass",
    name: "Sunglass",
    image: "/categories/sunglass.png",
    subCategories: [
      { searchTag: "sunglass", name: "Sunglass" },
      { searchTag: "women-sunglass", name: "Women Sunglass" },
      { searchTag: "baby-sunglasses", name: "Baby Sunglasses" },
      { searchTag: "party-sunglass", name: "Party Sunglass" },
      { searchTag: "goggles", name: "Goggles" },
      { searchTag: "reading-glasses", name: "Reading Glasses" },
    ],
  },
  {
    tag: "phone-accessories",
    name: "Phone Accessories",
    image: "/categories/phone-accessories.png",
    subCategories: [
      { searchTag: "xiaomi", name: "Xiaomi" },
      { searchTag: "apple", name: "Apple" },
      { searchTag: "huawei", name: "Huawei" },
      { searchTag: "realme", name: "Realme" },
      { searchTag: "one-plus", name: "One Plus" },
      { searchTag: "samsung", name: "Samsung" },
      { searchTag: "google", name: "Google" },
      { searchTag: "vivo-smartphone", name: "Vivo" },
      { searchTag: "nokia", name: "Nokia" },
      { searchTag: "lg", name: "LG" },
      { searchTag: "tecno", name: "Tecno" },
      { searchTag: "htc", name: "HTC" },
      { searchTag: "motorola", name: "Motorola" },
      { searchTag: "asus", name: "Asus" },
    ],
  },
  {
    tag: "fitness",
    name: "Fitness",
    image: "/categories/fitness.png",
    subCategories: [
      { searchTag: "snowboard", name: "Snowboard" },
      { searchTag: "jet-ski", name: "Jet Ski" },
      { searchTag: "swimming", name: "Swimming" },
      { searchTag: "fishing-rod", name: "Fishing Rod" },
      { searchTag: "bbq", name: "Grills & Bbq Equipment" },
      { searchTag: "luggage-lock", name: "Luggage Lock" },
      { searchTag: "yoga", name: "Yoga" },
      { searchTag: "tent", name: "Tent" },
    ],
  },
  {
    tag: "watches",
    name: "Watches",
    image: "/categories/watches.png",
    subCategories: [
      { searchTag: "watch", name: "Watch" },
      { searchTag: "womens-watch", name: "Womens Watch" },
      { searchTag: "mens-watches", name: "Mens Watches" },
      { searchTag: "smart-watch", name: "Smart Watch" },
      { searchTag: "gshock", name: "Gshock" },
      { searchTag: "apple-watch", name: "Apple Watch" },
      { searchTag: "fit-band", name: "Fit Band" },
    ],
  },
  {
    tag: "food-items",
    name: "Food Items",
    image: "/categories/food-items.png",
    subCategories: [
      { searchTag: "breakfast", name: "Breakfast" },
      { searchTag: "laundry-&-household", name: "Laundry & Household" },
      { searchTag: "cat", name: "Cat" },
      { searchTag: "cat-bag", name: "Cat Bag" },
      { searchTag: "dog", name: "Dog" },
      { searchTag: "fish", name: "Fish" },
      { searchTag: "bird", name: "Bird" },
      { searchTag: "small-pet", name: "Small Pet" },
    ],
  },
  {
    tag: "traveling",
    name: "Traveling",
    image: "/categories/traveling.png",
    subCategories: [
      { searchTag: "fishing-reel", name: "Fishing Reel" },
      { searchTag: "fishing", name: "Fishing" },
      { searchTag: "fishing-line", name: "Fishing Line" },
      { searchTag: "fishing-rod", name: "Fishing Rod" },
      { searchTag: "sportswear", name: "Sportswear" },
      { searchTag: "sports-bag", name: "Sports Bag" },
      { searchTag: "sport-accessories", name: "Sport Accessories" },
      { searchTag: "camping-&-hiking", name: "Camping & Hiking" },
      { searchTag: "hunting", name: "Hunting" },
      { searchTag: "fitness-&-bodybuilding", name: "Fitness & Bodybuilding" },
      { searchTag: "skiing-&-snowboarding", name: "Skiing & Snowboarding" },
    ],
  },
  {
    tag: "gadgets",
    name: "Gadgets",
    image: "/categories/gadgets.png",
    subCategories: [
      { searchTag: "electronics", name: "Electronics" },
      { searchTag: "camera", name: "Camera" },
      { searchTag: "mobile-accessories", name: "Mobile Accessories" },
      { searchTag: "computer-accessories", name: "Computer Accessories" },
      { searchTag: "gps-&-navigation", name: "Gps & Navigation" },
      { searchTag: "speaker", name: "Speaker" },
      { searchTag: "security-&-surveillance", name: "Security & Surveillance" },
      { searchTag: "tv", name: "Television" },
      { searchTag: "projector", name: "Projector" },
    ],
  },
];
