export const formattedRegistrationCountries = [
  {
    currency: "BDT",
    sign: "৳",
    countryCode: "BD",
    countryName: "Bangladesh",
    phoneCode: "+880",
    threeDigitCode: "BGD",
    flag: "https://flagcdn.com/w40/bd.png",
    states: [
      {
        name: "Dhaka",
        districts: [
          "Dhaka",
          "Gazipur",
          "Tangail",
          "Kishoreganj",
          "Manikganj",
          "Munshiganj",
          "Narayanganj",
          "Narsingdi",
          "Rajbari",
          "Faridpur",
          "Madaripur",
          "Gopalganj",
          "Shariatpur",
        ],
      },
      {
        name: "Chattogram",
        districts: [
          "Chattogram",
          "Cox's Bazar",
          "Rangamati",
          "Khagrachari",
          "Bandarban",
          "Noakhali",
          "Feni",
          "Lakshmipur",
          "Cumilla",
          "Brahmanbaria",
          "Chandpur",
        ],
      },
      {
        name: "Khulna",
        districts: [
          "Khulna",
          "Jashore",
          "Satkhira",
          "Bagerhat",
          "Narail",
          "Magura",
          "Jhenaidah",
          "Chuadanga",
          "Kushtia",
          "Meherpur",
        ],
      },
      {
        name: "Rajshahi",
        districts: [
          "Rajshahi",
          "Bogura",
          "Pabna",
          "Naogaon",
          "Natore",
          "Joypurhat",
          "Chapainawabganj",
          "Sirajganj",
        ],
      },
      {
        name: "Barishal",
        districts: [
          "Barishal",
          "Bhola",
          "Jhalokathi",
          "Patuakhali",
          "Barguna",
          "Pirojpur",
        ],
      },
      {
        name: "Sylhet",
        districts: ["Sylhet", "Moulvibazar", "Habiganj", "Sunamganj"],
      },
      {
        name: "Rangpur",
        districts: [
          "Rangpur",
          "Dinajpur",
          "Kurigram",
          "Thakurgaon",
          "Nilphamari",
          "Panchagarh",
          "Gaibandha",
          "Lalmonirhat",
        ],
      },
      {
        name: "Mymensingh",
        districts: ["Mymensingh", "Jamalpur", "Sherpur", "Netrokona"],
      },
    ],
  },
  {
    currency: "SAR",
    sign: "﷼",
    countryCode: "SA",
    countryName: "Saudi Arabia",
    phoneCode: "+966",
    threeDigitCode: "SAU",
    flag: "https://flagcdn.com/w40/sa.png",
    states: [{ name: "Saudi Arabia", districts: ["Saudi Arabia"] }],
  },
  {
    currency: "AED",
    sign: "د.إ",
    countryCode: "AE",
    countryName: "United Arab Emirates",
    phoneCode: "+971",
    threeDigitCode: "ARE",
    flag: "https://flagcdn.com/w40/ae.png",
    states: [
      { name: "United Arab Emirates", districts: ["United Arab Emirates"] },
    ],
  },
  {
    currency: "MYR",
    sign: "RM",
    countryCode: "MY",
    countryName: "Malaysia",
    phoneCode: "+60",
    threeDigitCode: "MYS",
    flag: "https://flagcdn.com/w40/my.png",
    states: [{ name: "Malaysia", districts: ["Malaysia"] }],
  },
  {
    currency: "INR",
    sign: "₹",
    countryCode: "IN",
    countryName: "India",
    phoneCode: "+91",
    threeDigitCode: "IND",
    flag: "https://flagcdn.com/w40/in.png",
    states: [{ name: "India", districts: ["India"] }],
  },
  {
    currency: "NPR",
    sign: "₨",
    countryCode: "NP",
    countryName: "Nepal",
    phoneCode: "+977",
    threeDigitCode: "NPL",
    flag: "https://flagcdn.com/w40/np.png",
    states: [{ name: "Nepal", districts: ["Nepal"] }],
  },
  {
    currency: "THB",
    sign: "฿",
    countryCode: "TH",
    countryName: "Thailand",
    phoneCode: "+66",
    threeDigitCode: "THA",
    flag: "https://flagcdn.com/w40/th.png",
    states: [{ name: "Thailand", districts: ["Thailand"] }],
  },
  {
    currency: "SGD",
    sign: "$",
    countryCode: "SG",
    countryName: "Singapore",
    phoneCode: "+65",
    threeDigitCode: "SGP",
    flag: "https://flagcdn.com/w40/sg.png",
    states: [{ name: "Singapore", districts: ["Singapore"] }],
  },
  {
    currency: "CNY",
    sign: "¥",
    countryCode: "CN",
    countryName: "China",
    phoneCode: "+86",
    threeDigitCode: "CHN",
    flag: "https://flagcdn.com/w40/cn.png",
    states: [{ name: "China", districts: ["China"] }],
  },
  {
    currency: "KWD",
    sign: "د.ك",
    countryCode: "KW",
    countryName: "Kuwait",
    phoneCode: "+965",
    threeDigitCode: "KWT",
    flag: "https://flagcdn.com/w40/kw.png",
    states: [{ name: "Kuwait", districts: ["Kuwait"] }],
  },
  {
    currency: "QAR",
    sign: "ر.ق",
    countryCode: "QA",
    countryName: "Qatar",
    phoneCode: "+974",
    threeDigitCode: "QAT",
    flag: "https://flagcdn.com/w40/qa.png",
    states: [{ name: "Qatar", districts: ["Qatar"] }],
  },
  {
    currency: "OMR",
    sign: "﷼",
    countryCode: "OM",
    countryName: "Oman",
    phoneCode: "+968",
    threeDigitCode: "OMN",
    flag: "https://flagcdn.com/w40/om.png",
    states: [{ name: "Oman", districts: ["Oman"] }],
  },
  {
    currency: "EUR",
    sign: "€",
    countryCode: "DE",
    countryName: "Germany",
    phoneCode: "+49",
    threeDigitCode: "DEU",
    flag: "https://flagcdn.com/w40/de.png",
    states: [{ name: "Germany", districts: ["Germany"] }],
  },
  {
    currency: "USD",
    sign: "$",
    countryCode: "US",
    countryName: "United States",
    phoneCode: "+1",
    threeDigitCode: "USA",
    flag: "https://flagcdn.com/w40/us.png",
    states: [{ name: "United States", districts: ["United States"] }],
  },
  {
    currency: "GBP",
    sign: "£",
    countryCode: "UK",
    countryName: "United Kingdom",
    phoneCode: "+44",
    threeDigitCode: "GBR",
    flag: "https://flagcdn.com/w40/gb.png",
    states: [{ name: "United Kingdom", districts: ["United Kingdom"] }],
  },
];
